print("Programmer: Jayson C Villanuz")
print("July 6, 2023")
print("Information")
print()
print("First Name: Jayson")
print("Middle Name: C")
print("Last Name: Villlanuz")
print("Course: BSIT")
print("Year: 3rd year")
print("Age: 20")
print("Gender: Male")
print("Civil statues: Single")
print("Nationality: Filipino")
print()
print("Motto: Honesty is the best policy")
print()
print("School: PHINMA Araullo University")
print("College: CITE")